steps:
  # 1. Lint with Spectral
  - name: 'stoplight/spectral:latest'
    args: ['lint', '${_SPEC_FILE}', '-r', 'linters/agentic.yaml']

  # 2. Register in API Hub
  - name: 'ghcr.io/apigee/apigeecli:latest'
    entrypoint: 'sh'
    args:
      - -c
      - |
        echo "Preparing API Hub payloads..."
        
        # Create api.json
        cat <<EOF > /tmp/api.json
        {
          "displayName": "${_DISPLAY_NAME}",
          "description": "Agentic Order API for demonstration",
          "owner": {
            "displayName": "API Team",
            "email": "api-team@example.com"
          },
          "apiStyle": {
            "attribute": "projects/${_PROJECT_ID}/locations/${_API_HUB_REGION}/attributes/system-api-style",
            "enumValues": {
              "values": [{ "id": "rest", "displayName": "REST", "description": "REST", "immutable": true }]
            }
          }
        }
        EOF

        # Create version.json
        cat <<EOF > /tmp/version.json
        {
          "displayName": "${_VERSION}",
          "lifecycle": {
             "attribute": "projects/${_PROJECT_ID}/locations/${_API_HUB_REGION}/attributes/system-lifecycle",
             "enumValues": {
               "values": [{ "id": "concept", "displayName": "Concept", "description": "Concept" }]
             }
          }
        }
        EOF
        
        echo "Registering in API Hub..."
        # Create API (ignore failure if exists)
        apigeecli apihub apis create -i ${_API_ID} -f /tmp/api.json -r ${_API_HUB_REGION} -o ${_PROJECT_ID} --default-token || echo "API ${_API_ID} might already exist, continuing..."
        
        # Create Version (ignore failure if exists)
        apigeecli apihub apis versions create --api-id ${_API_ID} -i ${_VERSION} -f /tmp/version.json -r ${_API_HUB_REGION} -o ${_PROJECT_ID} --default-token || echo "Version ${_VERSION} might already exist, continuing..."
        
        # Upload Spec (ignore failure if exists)
        apigeecli apihub apis versions specs create --api-id ${_API_ID} -v ${_VERSION} -i ${_SPEC_ID} -f ${_SPEC_FILE} -d "${_SPEC_ID}" -r ${_API_HUB_REGION} -o ${_PROJECT_ID} --default-token || echo "Spec ${_SPEC_ID} might already exist, continuing..."

  # 3. Deploy Proxy to Apigee
  - name: 'ghcr.io/apigee/apigeecli:latest'
    entrypoint: 'sh'
    args:
      - -c
      - |
        echo "Deploying to Apigee..."
        # Copy spec to /tmp to avoid permission issues
        cp ${_SPEC_FILE} /tmp/openapi.yaml
        cd /tmp
        
        # Create Proxy from Spec and Deploy
        apigeecli apis create openapi -n ${_PROXY_NAME} \
          --oas-base-folderpath . \
          --oas-name openapi.yaml \
          -o ${_APIGEE_ORG} --env ${_APIGEE_ENV} --wait --default-token

substitutions:
  _PROJECT_ID: "your-project-id"
  _APIGEE_ORG: "your-org"
  _APIGEE_ENV: "your-env"
  _API_HUB_REGION: "us-central1"
  _PROXY_NAME: "agentic-order-api"
  _API_ID: "agentic-order-api"
  _DISPLAY_NAME: "Agentic Order API"
  _VERSION: "v1-0-0"
  _SPEC_ID: "openapi-spec"
  _SPEC_FILE: "agentic/openapi.yaml"
